### ISSUE TITLE
Add the ability to configure the minimum account balance amount

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fdp-contracts#21]
It would be nice to be able to configure the minimum balance amount. 
It is worth considering that the minimum amount may not be static, but also dynamic. Most likely, need to be able to change its value after creating an instance of the class or be able to calculate the cost of registering an account on the fly and set it as the minimum value.

https://github.com/fairDataSociety/fdp-contracts/blob/c49abccf036f35096faf694f62f60a07c3c2150e/js-library/src/services/ens.ts#L25

**Comment by tfius** [comment]
has many issues when checking gas prices for different chains etc...

**Comment by IgorShadurin** [comment]
fixed with https://github.com/fairDataSociety/fdp-contracts/pull/142
