### ISSUE TITLE
ENS contracts: Separate identity into ethr-did and integrate existing PublicResolver contract with the latest ethr-did implementation

### ISSUE THREAD

**Issue by molekilla** [fairDataSociety/fdp-contracts#24]
PublicResolver contract is an address and identity resolver. There is already existing [EIP-1056 for Lightweight Ethereum Identities](https://eips.ethereum.org/EIPS/eip-1056) but  is currently DID oriented.

We can improve the PublicResolver if we add DID and multiformats where applicable to have universal compatible resolver for ENS, DID and also EIP-1056.

**1. Bare bones PublicResolver and separate ethr-did concerns to be integrated with EthereumDIDRegistry**
PublicResolver can inherit [EthereumDID](https://github.com/uport-project/ethr-did-registry/blob/develop/contracts/EthereumDIDRegistry.sol)

**2. Define identities using [CAIP-10](https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-10.md) with [`blockchainAccountId`](https://w3c.github.io/did-spec-registries/#blockchainaccountid)**
Allows the resolver to work with DID offchain features.

**3. Multiformat address**
Use existing Swarm definitions found [in  multicodec](https://github.com/multiformats/multicodec/blob/master/table.csv)

**Comment by molekilla** [comment]
https://github.com/w3c-ccg/did-pkh/blob/main/did-pkh-method-draft.md `did:pkh` PublicKeyHash supersedes `did:ethr`, we could either leave the ENS resolver as i s or add a `supportsDIDPublicKeyHash` or `supportsDIDPkh` and `getDIDPkh` to make it chain agnostic and compatible with the DID ecosystem.

**Comment by nugaon** [comment]
we could have DIDs in SoC/Feed topic conventions instead, but from a single ethereum address we can derive everything off-chain

**Comment by molekilla** [comment]
We can research this for SoC/Feed, closing it for fdp contracts for now
