### ISSUE TITLE
ci: blockchain image versioning on build and release

### ISSUE THREAD

**Issue by nugaon** [fairDataSociety/fdp-contracts#37]
the `fdp-contracts` root repository has its own `package.json` where its version number is defined.
This has to be the single-source-of-truth for all blockchain version related scripts within the repository.
Unfortunately, we have hard-coded values for now for building and releasing blockchain image of fdp-contracts in the `scripts/build-image.sh` and `scripts/release-image.sh`
We should rid of these hard-coded values regarding to the blockchain versions and use version defined in `package.json`

**Comment by crtahlin** [comment]
Is this finished, what is the status?

**Comment by crtahlin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fair-Data-Protocol-61f37a061754030017d022ea/issues/fairDataSociety/fdp-contracts/37?planning-poker) with ZenHub @tfius @molekilla

**Comment by molekilla** [comment]
done
