### ISSUE TITLE
ci: bump JS library version

### ISSUE THREAD

**Issue by nugaon** [fairDataSociety/fdp-contracts#38]
the [release-please action](https://github.com/googleapis/release-please) helps us to [bump the root project's version number](https://github.com/googleapis/release-please), but the release process also publishes the corresponding js-library of which version number is not bumped by release-please.
We have to add the version bumping feature to the current release-please GitHub action for the JS-library as well.

**Comment by crtahlin** [comment]
Is this finished, what is the status @molekilla ?

**Comment by crtahlin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fair-Data-Protocol-61f37a061754030017d022ea/issues/fairDataSociety/fdp-contracts/38?planning-poker) with ZenHub @tfius @molekilla

**Comment by molekilla** [comment]
completed by @nugaon
