### ISSUE TITLE
library for interacting with the contracts

### ISSUE THREAD

**Issue by nugaon** [fairDataSociety/fdp-contracts#4]
In order to facilitate the usage of the contracts, we should provide a JS library with which one can interact easily with the contracts on ganache testnet, later on goerli testnet and xdai mainnet.

On new smart contract definitions, also a JS library could be released with the corresponding ABIs and registered smart contract addresses. 
The library should be available on NPM that a CI workflow publishes on new version releases of the project.

**Comment by tfius** [comment]
i agree

**Comment by nugaon** [comment]
closed by https://github.com/fairDataSociety/fdp-contracts/pull/5
