### ISSUE TITLE
BLOCKER: Hotfix: CI issues with FDS register

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fdp-contracts#51]

**Comment by jayolin** [comment]
<img width="1021" alt="Screen Shot 2022-07-14 at 5 44 28 PM" src="https://user-images.githubusercontent.com/9630614/179034702-39441156-65f8-4852-9a5a-9c69f8f3513a.png">
`

**Comment by molekilla** [comment]
@crtahlin @nugaon fixed

https://github.com/fairDataSociety/fdp-contracts/pull/63

**Comment by crtahlin** [comment]
done, closing

**Comment by crtahlin** [comment]
done, closing
