### ISSUE TITLE
Manually configure release PRs

### ISSUE THREAD

**Issue by nugaon** [fairDataSociety/fdp-contracts#58]
with #53 the js-library and the contracts have two different release-please workflow. the version prefixes have been changed and the release PRs (#57  and #56) assumes the first version deployments that we had already.

we should configure the release PRs to bump the latest versions of the projects and update the changelogs manually

**Comment by nugaon** [comment]
#57 is completed, #56 should be updated after #46 has been resolved.

**Comment by crtahlin** [comment]
@nugaon please re-assign to appropriate person.

**Comment by crtahlin** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fair-Data-Protocol-61f37a061754030017d022ea/issues/fairDataSociety/fdp-contracts/58?planning-poker) with ZenHub @nugaon

**Comment by nugaon** [comment]
this has been resolved in the linked PRs already
